name: Build and Publish bedops

on:
  push:
    paths: 
      - 'bedops/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build, Tag, Publish Docker
      uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
      with:
        name: gwas/bedops
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        dockerfile: bedops/Dockerfile
