name: Build and Publish Docker Images

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build, Tag, Publish Docker
      uses: ./.github/actions/build-image
      with:
        organization: gwas
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
